apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordcount-api
spec:
  selector:
    matchLabels:
      run: discordcount-api
  replicas: 2
  template:
    metadata:
      labels:
        run: discordcount-api
    spec:
      containers:
      - name: discordcount-api
        image: registry.jakegealer.me/discordcount_api
        ports:
        - containerPort: 8000
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: RETHINKDB_HOSTNAME
          value: rethinkdb-rethinkdb-cluster
        - name: RETHINKDB_PASSWORD
          value: rethinkdb
      imagePullSecrets:
      - name: private-registry
---
apiVersion: v1
kind: Service
metadata:
  name: discordcount-api
  labels:
    run: discordcount-api
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    run: discordcount-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: discordcount-api-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - api.discordcount.me
    secretName: discordcount-prod-letsencrypt
  rules:
  - host: api.discordcount.me
    http:
      paths:
      - path: /
        backend:
          serviceName: discordcount-api
          servicePort: 8000
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: discordcount-prod-letsencrypt
spec:
  secretName: discordcount-prod-letsencrypt
  dnsNames:
  - api.discordcount.me
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - api.discordcount.me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
