apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
  - hosts:
    - registry.jakegealer.me
    secretName: registry-prod-letsencrypt
  rules:
  - host: registry.jakegealer.me
    http:
      paths:
      - path: /
        backend:
          serviceName: docker-registry
          servicePort: 5000
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: registry-prod-letsencrypt
spec:
  secretName: registry-prod-letsencrypt
  dnsNames:
  - registry.jakegealer.me
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - registry.jakegealer.me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
