apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-ai
spec:
  selector:
    matchLabels:
      run: message-ai
  replicas: 2
  template:
    metadata:
      labels:
        run: message-ai
    spec:
      containers:
      - name: message-ai
        image: jakemakesstuff/message-ai
        ports:
        - containerPort: 8000
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: RETHINK_HOST
          value: rethinkdb-rethinkdb-cluster
        - name: RETHINK_PASSWORD
          value: rethinkdb
      imagePullSecrets:
      - name: docker-hub
---
apiVersion: v1
kind: Service
metadata:
  name: message-ai
  labels:
    run: message-ai
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    run: message-ai
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ai-prod-letsencrypt
spec:
  secretName: ai-prod-letsencrypt
  dnsNames:
  - ai.jakegealer.me
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - ai.jakegealer.me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: message-ai-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - ai.jakegealer.me
    secretName: ai-prod-letsencrypt
  rules:
  - host: ai.jakegealer.me
    http:
      paths:
      - path: /
        backend:
          serviceName: message-ai
          servicePort: 8000
