apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: magiccap-api-prod-letsencrypt
spec:
  secretName: magiccap-api-prod-letsencrypt
  dnsNames:
  - api.magiccap.me
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - api.magiccap.me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
