apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jg-root-prod-letsencrypt
spec:
  secretName: jg-root-prod-letsencrypt
  dnsNames:
    - jakegealer.me
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - jakegealer.me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
