apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jakegealer-me
spec:
  replicas: 2
  serviceName: jakegealer-me
  selector:
    matchLabels:
      run: jakegealer-me
  template:
    metadata:
      labels:
        run: jakegealer-me
    spec:
      containers:
      - name: jakegealer-me
        image: registry.gitlab.com/jakemakesstuff/jakegealer-me
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            port: 80
            path: /
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            port: 80
            path: /
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "25Mi"
            cpu: "0.1"
          limits:
            memory: "128Mi"
            cpu: "0.1"
      imagePullSecrets:
      - name: gitlab
