apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: discordcount-prod-letsencrypt
spec:
  secretName: discordcount-prod-letsencrypt
  dnsNames:
  - api.discordcount.me
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - api.discordcount.me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
